### ISSUE TITLE
PubSubMessage.getChannel() does not work

### ISSUE THREAD

**Issue by 00pflaume** [minecrafter/RedisBungee#28]
I get an error when I want to ask for the channel via pEvent[This is my PubSubMessage Event].getChannel(). It throws this error:
20:27:28 [SCHWERWIEGEND] Dez 09, 2015 8:27:28 PM net.md_5.bungee.event.EventBus post
WARNUNG: Error dispatching event PubSubMessageEvent(channel=redisbungee-data, message={"target":"3940d785-6497-4098-b240-78542d84c8af","source":"test1","action":"LEAVE","payload":{"timestamp":1449689248547}}) to listener de.simonsator.partyandfriends.redisconnection.BungeeCommunicate@5d534f5d
java.lang.NoSuchMethodError: com.imaginarycode.minecraft.redisbungee.events.PubSubMessageEvent.getChannel()Ljava/lang/Object;
	at de.simonsator.partyandfriends.redisconnection.BungeeCommunicate.onMessageReceive(BungeeCommunicate.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
	at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:374)
	at com.imaginarycode.minecraft.redisbungee.RedisBungee$JedisPubSubHandler$1.run(RedisBungee.java:523)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by minecrafter** [comment]
Not a RedisBungee issue.

`PubSubMessageEvent.getChannel()` doesn't return `Object`. This is likely an issue with the JAR you're using. Redownload it and try again.
