### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by caoli5288** [minecrafter/RedisBungee#40]
Spam like those
```
警告: Error dispatching event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@4ad20a5c, receiver=wwwwwweeeeew), cancelled=false, tag=RedisBungee, data=[0, 11, 80, 108, 97, 121, 101, 114, 67, 111, 117, 110, 116, 0, 5, 85, 72, 67, 45, 51]) to listener com.imaginarycode.minecraft.redisbungee.RedisBungeeListener@72bdd7c7
java.util.concurrent.RejectedExecutionException: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@53e76c11, id=2007334, owner=com.imaginarycode.minecraft.redisbungee.RedisBungee@2fd64b11, task=com.imaginarycode.minecraft.redisbungee.RedisBungeeListener$5@378c753e, delay=0, period=0, running=true) rejected from java.util.concurrent.ThreadPoolExecutor@6f44a450[Running, pool size = 32, active threads = 31, queued tasks = 0, completed tasks = 1807226]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at net.md_5.bungee.scheduler.BungeeScheduler.schedule(BungeeScheduler.java:101)
	at net.md_5.bungee.scheduler.BungeeScheduler.schedule(BungeeScheduler.java:85)
	at net.md_5.bungee.scheduler.BungeeScheduler.runAsync(BungeeScheduler.java:79)
	at com.imaginarycode.minecraft.redisbungee.RedisBungeeListener.onPluginMessage(RedisBungeeListener.java:153)
	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
	at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:377)
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:226)
	at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:51)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:77)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:354)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)


11:06:11 [严重] 六月 26, 2016 11:06:11 上午 net.md_5.bungee.event.EventBus post
警告: Error dispatching event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@29ca0999, receiver=1xiao1xx), cancelled=false, tag=RedisBungee, data=[0, 11, 80, 108, 97, 121, 101, 114, 67, 111, 117, 110, 116, 0, 16, 77, 97, 115, 116, 101, 114, 66, 117, 105, 108, 100, 101, 114, 45, 49, 57]) to listener com.imaginarycode.minecraft.redisbungee.RedisBungeeListener@72bdd7c7
java.util.concurrent.RejectedExecutionException: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@53e76c11, id=2007322, owner=com.imaginarycode.minecraft.redisbungee.RedisBungee@2fd64b11, task=com.imaginarycode.minecraft.redisbungee.RedisBungeeListener$5@42f965b, delay=0, period=0, running=true) rejected from java.util.concurrent.ThreadPoolExecutor@6f44a450[Running, pool size = 32, active threads = 31, queued tasks = 0, completed tasks = 1807226]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at net.md_5.bungee.scheduler.BungeeScheduler.schedule(BungeeScheduler.java:101)
	at net.md_5.bungee.scheduler.BungeeScheduler.schedule(BungeeScheduler.java:85)
	at net.md_5.bungee.scheduler.BungeeScheduler.runAsync(BungeeScheduler.java:79)
	at com.imaginarycode.minecraft.redisbungee.RedisBungeeListener.onPluginMessage(RedisBungeeListener.java:153)
	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
	at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:377)
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:226)
	at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:51)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:77)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:354)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by caoli5288** [comment]
Seen like ThreadPool full?
