### ISSUE TITLE
Player could not connect to a back-end occasionally after resume from an unstable Redis connection

### ISSUE THREAD

**Issue by k-jiang** [minecrafter/RedisBungee#52]
Exception occasionally while player connect to BungeeCord. Notice that `/glist` can display player list with no issue.
```
14:33:46 [SEVERE] [RedisBungee] Unable to fix up stored player data
com.imaginarycode.minecraft.redisbungee.internal.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
    at com.imaginarycode.minecraft.redisbungee.internal.jedisutil.Pool.getResource(Pool.java:50)
    at com.imaginarycode.minecraft.redisbungee.internal.jedis.JedisPool.getResource(JedisPool.java:99)
    at com.imaginarycode.minecraft.redisbungee.RedisBungee$3.run(RedisBungee.java:310)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)
Caused by: com.imaginarycode.minecraft.redisbungee.internal.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection timed out (Connection timed out)
    at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.connect(Connection.java:164)
    at com.imaginarycode.minecraft.redisbungee.internal.jedis.BinaryClient.connect(BinaryClient.java:80)
    at com.imaginarycode.minecraft.redisbungee.internal.jedis.BinaryJedis.connect(BinaryJedis.java:1676)
    at com.imaginarycode.minecraft.redisbungee.internal.jedis.JedisFactory.makeObject(JedisFactory.java:87)
    at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
    at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435)
    at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
    at com.imaginarycode.minecraft.redisbungee.internal.jedisutil.Pool.getResource(Pool.java:48)
    ... 9 more
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.connect(Connection.java:158)
    ... 16 more
```

Tested on:
Waterfall build 134 https://ci.destroystokyo.com/job/Waterfall/
(same as BungeeCord build 1252)
RedisBungee 0.4

**Comment by KSchreuder** [comment]
It seems that RedisBungee can't connect to the Redis server
Double check if your Redis server is running correctly.
