### ISSUE TITLE
Error in bungee cord stop

### ISSUE THREAD

**Issue by JavituRec** [minecrafter/RedisBungee#53]
Hello,

I have 2 bungee cords (1 its premium and the other is no premium) with redis and redissbungee.

when the bungee cord (no premium) stop get a error in console:

`[SEVERE] Exception disabling plugin RedisBungee
com.imaginarycode.minecraft.redisbungee.internal.jedis.exceptions.JedisConnectionException: JedisPubSub was not subscribed to a Jedis instance.
    at com.imaginarycode.minecraft.redisbungee.internal.jedis.JedisPubSub.unsubscribe(JedisPubSub.java:41)
    at com.imaginarycode.minecraft.redisbungee.RedisBungee$PubSubListener.poison(RedisBungee.java:541)
    at com.imaginarycode.minecraft.redisbungee.RedisBungee.onDisable(RedisBungee.java:378)
    at net.md_5.bungee.BungeeCord$4.run(BungeeCord.java:415)`

**Comment by Chnkr** [comment]
User error, stop redis after you stop bungee
